name: RealViewDontTouch
main: fr.crafter.tickleman.realviewdonttouch.RealViewDontTouchPlugin
version: 0.10
website: http://plugins.crafter.fr/tickleman/RealViewDontTouch/
author: tickleman
depend: [RealPlugin,Spout]
commands:
  viewonly:
    description: Content can only be viewed, not touched
    usage: Click the chest you want to be protected
